### ISSUE TITLE
setting density of .tiff file not working in lambda env

### ISSUE THREAD

**Issue by mathewzilla** [Umkus/lambda-layer-sharp#21]
Hello, thanks for providing this repo. 
I have hit a problem. I want to set the `density` of a `.tiff` file in a lambda. The code works perfectly when running locally using `sharp`, but not in the lambda env. Example code that works/doesn't:

```
 const printFileContent = await sharp(printFileName)
    .toFormat('tiff', {
      compression: 'none',
    })
    .withMetadata({
      density: 300,
    })
    .toBuffer();
```

any ideas why this would work locally but not when using the layer? Other sharp functionality works (converting to `.tiff`, setting compression, attaching `.icc` color profiles etc). Thanks in advance.

**Comment by Umkus** [comment]
I frankly have no clue. Did you consider raising an issue in the sharp repo?
