### ISSUE TITLE
Compatiblity with other NodeJS version?

### ISSUE THREAD

**Issue by ShivamJoker** [Umkus/lambda-layer-sharp#24]
Hey thanks for this but I would like to know how we can make this compatible with other nodejs versions like 14,16 and 18

**Comment by Umkus** [comment]
Hello!
Please check the [README.md](https://github.com/Umkus/lambda-layer-sharp#getting).

You can now have the layer for all supported node runtimes and architectures

**Comment by ShivamJoker** [comment]
Thanks
