### ISSUE TITLE
gif support

### ISSUE THREAD

**Issue by Dramex** [Umkus/lambda-layer-sharp#4]
Hi, can i get one that support gif
https://github.com/lovell/sharp/pull/2012#issuecomment-567397176

**Comment by pistachiomatt** [comment]
Just stumbled on your repo and looking for quick GIF support too! Figuring out the libvips Docker installation took a whole day and I got nowhere.

**Comment by Umkus** [comment]
Unfortunately I'm unsure how to implement this. You'll have to follow the suggestions from the linked issue.
