### ISSUE TITLE
Building contains warning about libvips

### ISSUE THREAD

**Issue by jmonsma** [Umkus/lambda-layer-sharp#5]
Hi 

Im trying to build it myself to use it as a layer, but during building i get the following warning.

WARNING in ./node_modules/sharp/lib/libvips.js 54:23-70Critical dependency: the request of a dependency is an expression.

Does it really contain the libvips library?

**Comment by Umkus** [comment]
Hello, this is just [a warning](https://github.com/webpack/webpack/issues/196) from Webpack, it's safe to ignore it.
